// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC83tQmpfGCxFyvUkWmvZQSucuQeliSmcU',
    appId: '1:1095041276386:web:525bff427b33d2153dc1bb',
    messagingSenderId: '1095041276386',
    projectId: 'x-trainer-f3427',
    authDomain: 'x-trainer-f3427.firebaseapp.com',
    storageBucket: 'x-trainer-f3427.firebasestorage.app',
    measurementId: 'G-LPJY81V099',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT5rEb8eEtC6z6cRKM7ZTDYB3UGtbtjDg',
    appId: '1:1095041276386:android:f108f74357f2cb613dc1bb',
    messagingSenderId: '1095041276386',
    projectId: 'x-trainer-f3427',
    storageBucket: 'x-trainer-f3427.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC34DIgqOL-3qwms3jjYy7XqYSz-tvH7mw',
    appId: '1:1095041276386:ios:1224ed90d6407acb3dc1bb',
    messagingSenderId: '1095041276386',
    projectId: 'x-trainer-f3427',
    storageBucket: 'x-trainer-f3427.firebasestorage.app',
    iosBundleId: 'com.example.xTrainer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC34DIgqOL-3qwms3jjYy7XqYSz-tvH7mw',
    appId: '1:1095041276386:ios:1224ed90d6407acb3dc1bb',
    messagingSenderId: '1095041276386',
    projectId: 'x-trainer-f3427',
    storageBucket: 'x-trainer-f3427.firebasestorage.app',
    iosBundleId: 'com.example.xTrainer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC83tQmpfGCxFyvUkWmvZQSucuQeliSmcU',
    appId: '1:1095041276386:web:d5bd64b4af69ff233dc1bb',
    messagingSenderId: '1095041276386',
    projectId: 'x-trainer-f3427',
    authDomain: 'x-trainer-f3427.firebaseapp.com',
    storageBucket: 'x-trainer-f3427.firebasestorage.app',
    measurementId: 'G-XVZRE51652',
  );

}